-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 14:07:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemplo_escuela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo_escuela` ;

-- -----------------------------------------------------
-- Schema ejemplo_escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo_escuela` ;
USE `ejemplo_escuela` ;

-- -----------------------------------------------------
-- Table `ejemplo_escuela`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_escuela`.`profesor` ;

CREATE TABLE IF NOT EXISTS `ejemplo_escuela`.`profesor` (
  `id_profesor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_escuela`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_escuela`.`alumno` ;

CREATE TABLE IF NOT EXISTS `ejemplo_escuela`.`alumno` (
  `id_alumno` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_escuela`.`profesor_has_alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_escuela`.`profesor_has_alumno` ;

CREATE TABLE IF NOT EXISTS `ejemplo_escuela`.`profesor_has_alumno` (
  `profesor_id_profesor` INT NOT NULL,
  `alumno_id_alumno` INT NOT NULL,
  PRIMARY KEY (`profesor_id_profesor`, `alumno_id_alumno`),
  INDEX `fk_profesor_has_alumno_alumno1_idx` (`alumno_id_alumno` ASC) VISIBLE,
  INDEX `fk_profesor_has_alumno_profesor_idx` (`profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_has_alumno_profesor`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `ejemplo_escuela`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_has_alumno_alumno1`
    FOREIGN KEY (`alumno_id_alumno`)
    REFERENCES `ejemplo_escuela`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_escuela`.`materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_escuela`.`materia` ;

CREATE TABLE IF NOT EXISTS `ejemplo_escuela`.`materia` (
  `id_materia` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `grado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_escuela`.`alumno_has_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_escuela`.`alumno_has_materia` ;

CREATE TABLE IF NOT EXISTS `ejemplo_escuela`.`alumno_has_materia` (
  `alumno_id_alumno` INT NOT NULL,
  `materia_id_materia` INT NOT NULL,
  PRIMARY KEY (`alumno_id_alumno`, `materia_id_materia`),
  INDEX `fk_alumno_has_materia_materia1_idx` (`materia_id_materia` ASC) VISIBLE,
  INDEX `fk_alumno_has_materia_alumno1_idx` (`alumno_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_has_materia_alumno1`
    FOREIGN KEY (`alumno_id_alumno`)
    REFERENCES `ejemplo_escuela`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_materia_materia1`
    FOREIGN KEY (`materia_id_materia`)
    REFERENCES `ejemplo_escuela`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
